use_frameworks!

platform :ios, '9.0'

target 'PubSub_Example' do
  pod 'PubSubSwift', :path => '../'

  target 'PubSub_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['SWIFT_VERSION'] = '5.1'
    end
  end
end
